language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
    - chmod +x gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - mkdir -p deploy
  - zip -r springboot2-website *
  - mv springboot2-website.zip deploy/springboot2-website.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot2-website
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
  - provider: codedeployk
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot2-website
    key: springboot2-website.zip
    bundle_type: zip
    application: springboot2-website
    deployment_group: springboot2-website
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - mmmsu@naver.com